import { createClientFromRequest } from 'npm:@base44/sdk@0.8.6';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);

    const { description, imageUrl } = await req.json();

    if (!description) {
      return Response.json({ error: 'Missing description' }, { status: 400 });
    }

    const HEYGEN_API_KEY = Deno.env.get('HEYGEN_API_KEY');
    
    if (!HEYGEN_API_KEY) {
      return Response.json({ error: 'HeyGen API key not configured' }, { status: 500 });
    }

    console.log('🎬 Creating professional video with HeyGen...');
    console.log('📝 User Request:', description);

    // 1. Detect language
    const detectLanguagePrompt = `Detect the language of this text and return ONLY the language name in English (Hebrew/English/Arabic/Spanish/etc): ${description}`;
    const languageResult = await base44.integrations.Core.InvokeLLM({
      prompt: detectLanguagePrompt
    });
    const detectedLanguage = languageResult?.trim() || 'Hebrew';
    console.log('🌍 Detected language:', detectedLanguage);

    // 2. Generate extended professional script (5+ minutes)
    const scriptPrompt = `Create a comprehensive, professional broadcast-quality script (750-1050 words) about: ${description}

Requirements:
- Write in ${detectedLanguage} language ONLY
- Duration: 5-7 minutes of narration
- Professional news/documentary tone with depth
- Structure:
  * Strong opening hook (30 seconds)
  * Detailed main content with multiple angles (4-5 minutes)
  * Background, context, and analysis (1-2 minutes)
  * Strong closing summary (30 seconds)
- Rich, detailed content - don't rush
- Natural speaking rhythm with transitions
- Include specific examples and context
- Make it informative and engaging

Return only the complete script text in ${detectedLanguage}.`;

    console.log('📝 Generating extended script (5+ minutes)...');
    const scriptResult = await base44.integrations.Core.InvokeLLM({
      prompt: scriptPrompt,
      add_context_from_internet: true
    });

    const script = scriptResult?.trim() || description;
    console.log('✅ Extended script generated:', script.length, 'characters');
    console.log('📊 Preview:', script.substring(0, 150) + '...');

    // 3. Generate professional background
    let backgroundUrl = imageUrl;
    if (!backgroundUrl) {
      const bgResult = await base44.integrations.Core.GenerateImage({
        prompt: 'Professional news studio background, modern TV broadcast set, blue and white colors, clean minimalist design, professional lighting, 16:9 aspect ratio, photorealistic'
      });
      backgroundUrl = bgResult.url;
      console.log('✅ Background created');
    }

    // 4. Select voice based on language
    let voiceId = 'v6WKRTqObgmv7NHgVAFD'; // Hebrew
    if (detectedLanguage.toLowerCase().includes('english')) {
      voiceId = 'EXAVITQu4vr4xnSDxMaL';
    } else if (detectedLanguage.toLowerCase().includes('arabic')) {
      voiceId = 'AZnzlk1XvdvUeBnXmlld';
    }
    console.log('🎤 Voice ID:', voiceId);

    // 5. Create HeyGen video using Avatar API (more reliable, lower cost)
    console.log('🎬 Calling HeyGen Avatar API...');
    console.log('📋 Script length:', script.length, 'characters');

    const heygenResponse = await fetch('https://api.heygen.com/v1/avatar/talk', {
      method: 'POST',
      headers: {
        'X-API-KEY': HEYGEN_API_KEY,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        text: script,
        avatar_id: 'Wayne_20240711',
        voice: {
          voice_id: voiceId,
          rate: 1.0
        },
        background: {
          color: '#000000'
        }
      })
    });

    const responseText = await heygenResponse.text();
    console.log('📥 HeyGen Response:', heygenResponse.status, responseText);

    if (!heygenResponse.ok) {
      console.error('❌ HeyGen error:', heygenResponse.status, responseText);
      return Response.json({ 
        error: `HeyGen API error: ${responseText}`,
        status: heygenResponse.status
      }, { status: 500 });
    }

    const heygenData = JSON.parse(responseText);
    console.log('📦 Full HeyGen Response:', JSON.stringify(heygenData, null, 2));
    
    // Avatar API returns different structure
    const videoId = heygenData.data?.video_id || heygenData.video_id || heygenData.data?.id || heygenData.id;
    
    if (!videoId) {
      console.error('❌ No video ID in response. Full data:', heygenData);
      return Response.json({ 
        error: 'No video ID returned from HeyGen',
        details: heygenData
      }, { status: 500 });
    }

    console.log('✅ Video generation started! video_id:', videoId);

    return Response.json({
      video_id: videoId,
      status: 'processing',
      message: 'Video is being generated by HeyGen Video Agent'
    });

  } catch (error) {
    console.error('🔴 Error:', error);
    return Response.json({ error: error.message }, { status: 500 });
  }
});